# Generated by Django 4.0.3 on 2022-03-25 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Texto', models.CharField(max_length=840)),
            ],
        ),
        migrations.CreateModel(
            name='Posteos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=40)),
                ('Autor', models.CharField(max_length=20)),
                ('Fecha', models.DateTimeField(verbose_name=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Suscriptores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=10)),
                ('Gusto', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
