# Generated by Django 4.0.3 on 2022-03-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contacto_posteos_suscriptores_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteos',
            name='Texto',
            field=models.TextField(default='Texto de Prueba'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Texto',
            field=models.TextField(),
        ),
    ]
