# Generated by Django 4.0.3 on 2022-03-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_posteos_texto_alter_contacto_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Texto', models.TextField()),
            ],
        ),
    ]
